package com.upgrad.quora.api.controller;

import com.upgrad.quora.api.model.QuestionDetailsResponse;
import com.upgrad.quora.api.model.QuestionEditRequest;
import com.upgrad.quora.api.model.QuestionRequest;
import com.upgrad.quora.api.model.QuestionResponse;
import com.upgrad.quora.service.business.QuestionBusinessService;
import com.upgrad.quora.service.entity.QuestionEntity;
import com.upgrad.quora.service.exception.AuthorizationFailedException;
import com.upgrad.quora.service.exception.InvalidQuestionException;
import com.upgrad.quora.service.exception.UserNotFoundException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

@RestController
@RequestMapping("/")
public class QuestionController {

    /**
     * This class handles all the endpoints pertaining to QuestionEntity (question table) in database.
     *
     * This class uses the QuestionBusinessService class which is autowired and thus instantiated
     * by Spring Framework for us.
     */

    @Autowired
    private QuestionBusinessService questionBusinessService;

    /**
     * @param questionRequest
     * @param authorization
     * @return
     * @throws AuthorizationFailedException
     * @throws UserNotFoundException
     */
    @RequestMapping(method = RequestMethod.POST,
            path = "/question/create",
            consumes = MediaType.APPLICATION_JSON_UTF8_VALUE,
            produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
    public ResponseEntity<QuestionResponse> createQuestion(final QuestionRequest questionRequest,
                                                           @RequestHeader("authorization") final String authorization)
            throws AuthorizationFailedException, UserNotFoundException {
        QuestionEntity questionEntity = questionBusinessService.createQuestion(questionRequest.getContent(), authorization);

        final QuestionResponse questionResponse = new QuestionResponse().id(questionEntity.getUuid()).status("QUESTION CREATED");
        return new ResponseEntity<>(questionResponse, HttpStatus.OK);
    }

    /**
     * @param authorization
     * @return
     * @throws AuthorizationFailedException
     */
    @RequestMapping(method = RequestMethod.GET,
            path = "/question/all",
            produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
    public ResponseEntity<List<QuestionDetailsResponse>> getAllQuestions(@RequestHeader("authorization") final String authorization)
            throws AuthorizationFailedException {
        List<QuestionEntity> allQuestions = questionBusinessService.getAllQuestions(authorization);
        List<QuestionDetailsResponse> allQuestionResponse = new ArrayList<>();

        for (QuestionEntity question : allQuestions) {
            allQuestionResponse.add(new QuestionDetailsResponse().id(question.getUuid())
                    .content(question.getContent()));
        }

        return new ResponseEntity<>(allQuestionResponse, HttpStatus.OK);
    }

    /**
     * @param questionUuid
     * @param questionEditRequest
     * @param authorization
     * @return
     * @throws AuthorizationFailedException
     * @throws InvalidQuestionException
     */
    @RequestMapping(method = RequestMethod.PUT,
            path = "/question/edit/{questionId}",
            consumes = MediaType.APPLICATION_JSON_UTF8_VALUE,
            produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
    public ResponseEntity<QuestionResponse> editQuestion(@PathVariable("questionId") final String questionUuid,
                                                         final QuestionEditRequest questionEditRequest,
                                                         @RequestHeader("authorization") final String authorization)
            throws AuthorizationFailedException, InvalidQuestionException {

        //Question business service's editQuestion method is called to run the business logic of
        // editing question in database. It passes following as parameters:
        //1. Question UUID (input as path variables)
        //2. New Content for the respective question
        //3. User Auth token of the signed in user
        QuestionEntity questionEntity = questionBusinessService.editQuestion(questionUuid, questionEditRequest.getContent(), authorization);

        //Appropriate response model (generated by swagger 2.0) is instantiated/configured and returned as JSON.
        final QuestionResponse questionResponse = new QuestionResponse().id(questionEntity.getUuid()).status("QUESTION EDITED");
        return new ResponseEntity<>(questionResponse, HttpStatus.OK);
    }

    @RequestMapping(method = RequestMethod.DELETE,
            path = "/question/delete/{questionId}",
            produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
    public ResponseEntity<QuestionResponse> deleteQuestion(@PathVariable("questionId") final String questionUuid,
                                                           @RequestHeader("authorization") final String authorization)
            throws AuthorizationFailedException, InvalidQuestionException {

        //Question business service's deleteQuestion method is called to run the business logic of
        // delete question in database. It passes following as parameters:
        //1. Question UUID (input as path variables)
        //2. User Auth token of the signed in user
        QuestionEntity questionEntity = questionBusinessService.deleteQuestion(questionUuid, authorization);

        //Appropriate response model (generated by swagger 2.0) is instantiated/configured and returned as JSON.
        final QuestionResponse questionResponse = new QuestionResponse().id(questionEntity.getUuid()).status("QUESTION DELETED");
        return new ResponseEntity<>(questionResponse, HttpStatus.OK);
    }

    @RequestMapping(method = RequestMethod.GET,
            path = "question/all/{userId}",
            produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
    public ResponseEntity<List<QuestionDetailsResponse>> getAllQuestionsByUser(@PathVariable("userId") final String userUuid,
                                                                               @RequestHeader("authorization") final String authorization)
            throws AuthorizationFailedException, UserNotFoundException {

        //Question business service's getAllQuestionsByUser method is called to run the business logic of
        // getting questions of particular user from database. It passes following as parameters:
        //1. User UUID (input as path variables)
        //2. User Auth token of the signed in user

        //Get all answer as a list of AnswerEntity
        List<QuestionEntity> allQuestionsByUser = questionBusinessService.getAllQuestionsByUser(authorization, userUuid);
        List<QuestionDetailsResponse> allQuestionByUserResponse = new ArrayList<>();

        //Populate the list of response for each user using for each loop over allQuestionsByUser
        for (QuestionEntity question : allQuestionsByUser) {
            allQuestionByUserResponse.add(new QuestionDetailsResponse().id(question.getUuid())
                    .content(question.getContent()));
        }

        //Appropriate response model (generated by swagger 2.0) is instantiated/configured and returned as JSON.
        return new ResponseEntity<>(allQuestionByUserResponse, HttpStatus.OK);
    }
}